name: perpustakaan_mini
description: A new Flutter project for a mini digital library.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  url_launcher: ^6.1.14
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.5.3
  getwidget: any
  flutter_bloc: ^8.1.5
  internet_file: ^1.2.0
  dio: ^5.4.3+1
  equatable: ^2.0.5
  epub_view: ^3.0.1
  http: ^1.2.0
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png