name: perpustakaan_mini
description: A new Flutter project for a mini digital library.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  url_launcher: ^6.1.14
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.5.3
  getwidget: any
  flutter_bloc: ^9.1.1
  internet_file: ^1.2.0
  dio: ^5.4.3+1
  equatable: ^2.0.5
  epub_view: ^3.0.1
  http: ^1.2.0
  cached_network_image: ^3.4.1
  go_router: ^17.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.8
  mockito: ^5.4.4
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/logo.png"
  web:
    generate: true
    image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png